name: GenerateRelease
on:
  push:
    branches:
      - master

jobs:
  information:
    name: GitHub Context
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: echo "$GITHUB_CONTEXT"

  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          preset: 'conventionalcommits'
          git-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './package.json,./pnpm-lock.yaml'

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          git-branch: master
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
